---
- name: Update apt cache
  apt:
    update_cache: true

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - /etc/apt/keyrings
    - /etc/scylla/cassandra

- name: Install java
  apt:
    name: "{{ jdkversion }}"
